搭建标准IO实现架构
plctlab/mlibc pull request #16
Opened 2024-05-04 16:47 UTC by 0Bitbiscuits

根据PSE51增加stdio.h中的函数，添加了标准输入输出的接口声明，以及系统相关函数的接口声明

2024-05-06 10:25 UTC, BernardXiong commented on src/internal/stdio_impl.h
> +#ifndef MLIBC_STDIO_IMPL_H__
版权信息

2024-05-06 10:28 UTC, BernardXiong requested changes

2024-05-06 10:28 UTC, BernardXiong commented on src/rtthread/SConscript
> +from building import *
Good! 是需要到要考虑不同OS，硬件平台的移植了的，但对于目录需要想好，直接这样放置，还是说按照某种方式放置。如果有5种以上os的平台需要移植，这个时候怎么办？如果有5种以上硬件架构需要移植，这个时候又需要怎么办？

2024-05-06 16:08 UTC, 0Bitbiscuits commented on src/rtthread/SConscript
> +from building import *
我的思路是为架构和系统分别创建一个文件夹，在需要扩展时可以往对应的文件夹添加对应的实现

2024-05-08 03:18 UTC, BernardXiong approved these changes

2024-05-08 03:19 UTC, merged