将TLSF算法移植到mlibc中
plctlab/mlibc pull request #19
Opened 2024-05-15 09:23 UTC by 0Bitbiscuits

后续将使用TLSF提供的接口结合系统调用，实现malloc，free和realloc函数
实现思路：
裸机状态下，使用整个sram作为TLSF的内存池
操作系统状态下，使用系统调用作为内存块来源

2024-05-15 16:48 UTC, BernardXiong commented on include/sys/types.h
> +typedef unsigned long    ubase_t;
不建议使用 `ubase/base_t` 类型，使用ssize_t，size_t完全可以替代

2024-05-16 01:34 UTC, 0Bitbiscuits commented on include/sys/types.h
> +typedef unsigned long    ubase_t;
已删除

2024-05-17 10:04 UTC, BernardXiong requested changes

2024-05-17 10:04 UTC, BernardXiong commented on arch/stm32/config.h
> +/*
不存在`arch/stm32`一说，应该说更多的是`arch/cortex-m`， 或者`arch/cortex-m4` 等。arch指的不是芯片，而是体系架构

2024-05-17 10:04 UTC, BernardXiong commented on system/rtthread/include/sys_mem.h
> +#define sys_malloc(size) rt_malloc(size)
这部分反了

2024-05-19 03:07 UTC, 0Bitbiscuits commented on arch/arch_config.h
> +#include "stm32/config.h"
确实这个地方没有考虑到位

2024-05-19 03:09 UTC, 0Bitbiscuits commented on system/rtthread/include/sys_mem.h
> +#define sys_malloc(size) rt_malloc(size)
这部分的思路是，定义了RT_USING_HEAP则用rt-thread的实现去定义宏，没有则都是空实现

2024-05-19 03:10 UTC, 0Bitbiscuits commented on arch/stm32/config.h
> +/*
是的，我理解出错了，打算把这部分删除掉，不应该有的

2024-05-23 05:24 UTC, closed without merging