重新调整了内存管理部分的代码实现结构
plctlab/mlibc pull request #24
Opened 2024-05-27 10:11 UTC by 0Bitbiscuits

1. 添加了fflush，fclose，fopen函数
2. 重新调整了内存管理部分的代码实现：
具体调整如下：
- 在system文件夹下添加generic文件夹用于添加不同操作系统的通用模块
- 在generic文件夹下添加tlsf模块，用于存放使用tlsf算法实现的内存管理代码

2024-05-28 02:10 UTC, BernardXiong commented on system/rtthread/sys_fio/__mlibc_sys_close.c
> +    result = dfs_file_close(d);
RT-Thread的移植并不需要这样，因为RT-Thread本身已经带了fd的管理，open/read/write/close的支持。所以它是采用实现对应的函数，来替代弱符号的open/read/write/close的方式。

2024-05-28 02:11 UTC, BernardXiong requested changes
和RT-Thread整体移植相关的，都想得过于复杂了。这部分也可以参考下其他libc是怎么来对接的，或者对底层移植层是如何考虑的。

2024-05-28 07:59 UTC, 0Bitbiscuits commented
复杂指的是实现过于复杂嘛？还是说对于提供的接口过于复杂了。对于这部分的调整我的理解还不够清晰。

2024-05-28 09:57 UTC, 0Bitbiscuits commented
TLSF实现的内存管理的那部分代码，放在什么位置我也还不是很清晰。
目前的想法就是system下创建一个common目录或者是generic目录去存放，当需要用其它的内存管理算法扩展时也可以在这个位置去添加。

2024-05-31 15:35 UTC, BernardXiong approved these changes

2024-05-31 21:48 UTC, merged