添加cortex-a9和cortex-r52的裸机代码
plctlab/mlibc pull request #27
Opened 2024-06-13 09:54 UTC by 0Bitbiscuits

添加cortex-a9和cortex-r52的裸机测试代码
添加了cortex-a9和cortex-r52的裸机运行指南

2024-06-14 05:18 UTC, BernardXiong requested changes

2024-06-14 05:18 UTC, BernardXiong commented on testcase/hello_arm_cortex_a9/mlibc_start.c
> +/*
这个文件命名成main.c即可

2024-06-14 05:18 UTC, BernardXiong commented on testcase/hello_arm_cortex_r52/mlibc_start.c
> +/*
这个文件命名成main.c即可

2024-06-14 05:18 UTC, BernardXiong commented on testcase/hello_arm_cortex_r52/uart_pl011.c
> +/*
这份的和a9的差异为什么这么大呢？应该是可以统一的，不同点可能仅是外设寄存器基地址不一样

2024-06-14 05:18 UTC, BernardXiong commented on testcase/hello_arm_cortex_a9/uart_pl011.c
> +/*
需要追求极致极简，只存在三个文件：
* main.c
* startup.S
* link.ld

然后是编译的脚本（xmake构建脚本）。

2024-06-14 05:18 UTC, BernardXiong commented on testcase/hello_arm_cortex_r52/startup.s
> +_start:
R52的汇编是这样，A9的汇编是前面的，两者为什么差异这么大？是否逐句都清楚了？

2024-06-18 03:20 UTC, 0Bitbiscuits commented on testcase/hello_arm_cortex_r52/uart_pl011.c
> +/*
我刚开始是先跑a9的，一开始也是使用的a9的串口结构体以及初始化代码，后面它是没有办法输出的，所以我就使用了官方给的串口输出相关的代码，发现能够正常输出因此我就使用了这部分代码。一开始也有统一他们的想法，但是寄存器的位置两者也不同，有些寄存器的作用冲突了，例如a9的uart_base + 0x8是_reserved，而r52的uart_base + 0x8则是控制寄存器

2024-06-18 03:23 UTC, 0Bitbiscuits commented on testcase/hello_arm_cortex_r52/startup.s
> +_start:
一开始确实有些急功近利了，导致很多部分不清楚走了很多弯路，目前已经重新调整好了这部分的代码

2024-06-18 03:29 UTC, 0Bitbiscuits commented
在移植mlibc的过程中，我发现是可以正常使用原版本mlibc的，但是使用目前最新版本的mlibc就是会存在数据访问异常，我目前是怀疑mlibc的一些全局数据的地址没有对齐，最终导致了一些指令访问的地址有问题从而出现了异常，后续也会往这个方向去调整mlibc的代码。

2024-06-18 15:25 UTC, BernardXiong approved these changes

2024-06-18 15:25 UTC, merged