Support Spinlock
plctlab/mlibc pull request #32
Opened 2024-07-23 06:59 UTC by 0Bitbiscuits

1. 提供原子操作库：stdatomic.h
2. 使用原子操作函数实现spinlock为mlibc提供可重入支持做准备

2024-07-23 08:18 UTC, BernardXiong requested changes
代码风格请检查下。

另外，建议多考虑到后续arch的问题，也包括这其中可能也用到了gcc内置的一些code？如果更换了编译器会怎么办，如果是llvm呢？

2024-07-23 08:18 UTC, BernardXiong commented on include/stdatomic.h
> +typedef _Atomic(char)			    atomic_char;
这边对齐应该存在不一致

2024-07-24 11:13 UTC, 0Bitbiscuits commented
修改：
1. 给stdatomic模块添加相关宏便于后续扩展，目前只支持GNUC的原子操作

TODO：
1. 实现libc对mutex和sem的支持
2. 不依赖编译器，在libc中提供硬件原子操作

2024-07-25 09:56 UTC, BernardXiong approved these changes

2024-07-25 09:56 UTC, merged