add memcpy and Sconscript
plctlab/mlibc pull request #9
Opened 2023-04-05 16:23 UTC by linshire

memcpy在qemu-riscv测试通过

2023-04-07 06:07 UTC, BernardXiong requested changes

2023-04-07 06:07 UTC, BernardXiong commented on mlibc/SConscript
> +    LIBS = ['libabc_keil']
libabc？

2023-04-07 06:07 UTC, BernardXiong commented on mlibcout
> +#ifndef __STRING_H_
文件头的许可协议信息？

2023-04-08 16:31 UTC, BernardXiong requested changes

2023-04-08 16:31 UTC, BernardXiong commented on src/string.c
> +    return NULL;
这个是什么代码风格

2023-04-08 16:31 UTC, BernardXiong commented on xmake.lua
> +    os.cp("./include/*.h", "./mlibc")
需要安装，从而要做头文件复制？

2023-04-08 16:31 UTC, BernardXiong commented on xmake.lua
> +    os.cp("./mlibc", "../../mlibc-qemu-riscv64-test")
到 `mlibc-qemu-riscv64-test` ？

2023-04-08 16:31 UTC, BernardXiong commented on mlibc/SConscript
> +Import('rtconfig')
这个文件用于？

2023-04-09 07:28 UTC, linshire commented on xmake.lua
> +    os.cp("./include/*.h", "./mlibc")
将头文件以及.a文件打包

2023-04-09 07:29 UTC, linshire commented on xmake.lua
> +    os.cp("./mlibc", "../../mlibc-qemu-riscv64-test")
复制到测试bsp的目录，方便调试，没有该目录的话，不会复制过去

2023-04-09 07:29 UTC, linshire commented on mlibc/SConscript
> +Import('rtconfig')
不好意思，误写了

2023-04-10 06:33 UTC, closed without merging